### ISSUE TITLE
Quick correction Dutch "Trophies"

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/translations#11]
In the Dutch translation the Dutch word for "Trophies" is consequently misspelled in the same manner

```
  Trofee&eacuten
```

Would even get wrong as there is an HTML error, but also when you fix the HTML error you'd get "Trofeeén" which is a misspelling also.

It must be:

```
   Trofee&euml;n
```

That way you'll get "Trofeeën" which is the correct spelling. Both @Fappp and I already agreed on that one. However, replacing that all one by one in poeditor is going to be one hell of a job. Is it possible for you to replace them all in one go (With a "replace all" or something)? If so, you'd save us a LOT of work ;) (Since the word "Trophies" was used a lot).

**Comment by Fappp** [comment]
I'll fix this later today!

**Comment by hworld** [comment]
For these changes I can always sync the current translations to github, then you can send a PR to github changing the .po file (no more toml) and then I can sync those changes back to the POEditor site. Just let me know if you'd rather me do that.

**Comment by Tricky1975** [comment]
Well, it's only for this particular 'error' as it was a consistent one, which is done wrong in all the times the word "trophy" (or it's Dutch equivalent) occurred, and that is quite a lot of times, and doing that one by one in the POEditor site was a bit a crazy go.

**Comment by hworld** [comment]
Am I able to close this?

**Comment by Tricky1975** [comment]
I shall look into that. If Fappp didn't fix this already I shall make a pull request on this one. :wink:

**Comment by Fappp** [comment]
Close it! :dancer: 38 instances replaced on POE

**Comment by Tricky1975** [comment]
Thanks for pointing that out, Fappp :sunglasses:
