### ISSUE TITLE
POEditor List

### ISSUE THREAD

**Issue by Maikuolan** [gamejolt/translations#13]
This possibly may be a terrible idea, I'm not sure, but, I've created a repository for a list just now for the purposes of listing GitHub repositories that are also registered with POEditor, that are looking for and/or willing to accept translators, available here -> https://github.com/Maikuolan/GitHub-OS-POEditor-Projects-List

I found your repository by using the GitHub search functionality, and I noticed the "_All our copy in one repo so that we can translate into other languages. Use https://poeditor.com/join/project/B4nWT6EgnD to translate._" in your repository description.

Would you be interested in having your repository listed on this list, and would I have your permission to list it there? Cheers. :-)

PS, if this is a terrible idea, feel free to let me know, or to just close and ignore this issue.

**Comment by hworld** [comment]
Yeah, sure. Feel free to list it in there!

**Comment by Maikuolan** [comment]
Awesome! Cheers, and added. :-)
